project:
  type: website
  output-dir: docs
  
website:
  navbar:
    left:
      - href: index.qmd
        text: Profile
      - href: trading_bot_project.qmd
        text: Trading Bot Project
      - href: Data_Visualization.qmd
        text: Data Visualization
      - href: Reflection.qmd
        text: Reflection

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


